services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
  api:
    build:
      context: ./backend/servartur
      dockerfile: src/Servartur.Api/Dockerfile

    environment:
      ASPNETCORE_URLS: http://+:8080

    restart: unless-stopped